# Download the TensorFlow Serving Docker image and repo
#docker pull tensorflow/serving
from tensorflow/serving
#git clone https://github.com/tensorflow/serving
# Location of demo models
ENV TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"
