pull tensorflow/serving
git clone https://github.com/tensorflow/serving
# Location of demo models
TESTDATA="$(pwd)/serving/tensorflow_serving/servables/tensorflow/testdata"
run -p 8501:8501 --mount type=bind,source="/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu:/models/half_plus_two",target=/models/half_plus_two -e MODEL_NAME=half_plus_two -t tensorflow/serving
